<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-OVNCBGS" failures="2" tests="2" name="Default test(failed)" time="0.118" errors="0" timestamp="2022-06-01T20:21:02 IST">
  <testcase classname="testngdiscus.HardAssertionInTestNG" name="testCase1" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngdiscus.HardAssertionInTestNG.testCase1(HardAssertionInTestNG.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="testngdiscus.HardAssertionInTestNG" name="testCase4" time="0.006">
    <failure type="java.lang.AssertionError" message="test case fail deliberately">
      <![CDATA[java.lang.AssertionError: test case fail deliberately
at testngdiscus.HardAssertionInTestNG.testCase4(HardAssertionInTestNG.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 -->
  <testcase classname="testngdiscus.HardAssertionInTestNG" name="testCase2" time="0.0">
    <ignored/>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Default test(failed) -->
